/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef AMAZONIAP_AUTODEFS_H
#define AMAZONIAP_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_AMAZONIAP_NAME "AmazonIAP"
#define S3E_EXT_AMAZONIAP_HASH 0xfcc81ee5

#endif /* !AMAZONIAP_AUTODEFS_H */
