/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "AmazonIAP_autodefs.h"
#include "s3eEdk.h"
#include "AmazonIAP.h"
//Declarations of Init and Term functions
extern s3eResult AmazonIAPInit();
extern void AmazonIAPTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static s3eResult AmazonIAPStartPurchase_wrap(const char* productID)
{
    IwTrace(AMAZONIAP_VERBOSE, ("calling AmazonIAP func on main thread: AmazonIAPStartPurchase"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)AmazonIAPStartPurchase, 1, productID);
}

#define AmazonIAPStartPurchase AmazonIAPStartPurchase_wrap

#endif

s3eResult AmazonIAPRegister(AmazonIAPCallback cbid, s3eCallback fn, void* pData)
{
    return s3eEdkCallbacksRegister(S3E_EXT_AMAZONIAP_HASH, AMAZONIAP_CALLBACK_MAX, cbid, fn, pData, 0);
};

s3eResult AmazonIAPUnRegister(AmazonIAPCallback cbid, s3eCallback fn)
{
    return s3eEdkCallbacksUnRegister(S3E_EXT_AMAZONIAP_HASH, AMAZONIAP_CALLBACK_MAX, cbid, fn);
}

void AmazonIAPRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[3];
    funcPtrs[0] = (void*)AmazonIAPRegister;
    funcPtrs[1] = (void*)AmazonIAPUnRegister;
    funcPtrs[2] = (void*)AmazonIAPStartPurchase;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[3] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("AmazonIAP", funcPtrs, sizeof(funcPtrs), flags, AmazonIAPInit, AmazonIAPTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int AmazonIAPStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&AmazonIAPRegisterExt;
    return 0;
}

int g_AmazonIAPVal = AmazonIAPStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    AmazonIAPRegisterExt();
}
#endif

#endif
